#! /bin/sh
set -e

# Disable CD image in sources.list if any other sources are present
if ([ -e /cdrom/.disk/base_installable ] || [ "$OVERRIDE_BASE_INSTALLABLE" ]); then
	logger -t finish-install "Disabling CD in sources.list"
	sed -i "/^deb cdrom:/s/^/#/" /target/etc/apt/sources.list
fi

# Remove locale source
if ([ -e /target/etc/apt/sources.list.d/locale.list ]); then
    logger -t finish-install "Removing linuxmint locale source"
    rm -rf /target/etc/apt/sources.list.d/locale.list
fi
