#!/bin/sh -e
#Provides all mythbuntu questions asked by
#ubiquity during install process
# Written by Mario Limonciello <superm1@ubuntu.com>
# Copyright (C) 2007-2009 Mario Limonciello

. /usr/share/debconf/confmodule

if [ "$1" = "type" ]; then
    # Determine install type
    db_input high mythbuntu/install_type || true

elif [ "$1" = "drivers" ]; then
    #determine video. drivers
    db_input high mythbuntu/video_driver || true
    #determine tv out settings
    db_input high mythbuntu/tvout || true
    db_input high mythbuntu/tvstandard || true

elif [ "$1" = "ir" ]; then
    #remote controls
    db_input high lirc/remote || true
    #transmitter controls
    db_input high lirc/transmitter || true

elif [ "$1" = "services" ]; then
    #determine services
    db_input high mythbuntu/x11vnc || true
    db_input high mythbuntu/openssh-server || true
    db_input high mythbuntu/samba || true
    db_input high mythbuntu/nfs-kernel-server || true
    db_input high mythbuntu/mysql-server || true

elif [ "$1" = "passwords" ]; then
    #determine mysql info
    db_input high mythtv/mysql_mythtv_user || true
    db_input high mythtv/mysql_mythtv_password || true
    db_input high mythtv/mysql_mythtv_dbname || true
    db_input high mythtv/mysql_host || true
fi
