#!/bin/sh
# Used to Launch MythTV-Setup & MySQL as needed
# Copyright © 2007-2009  Mario Limonciello

ROOT="/target"
chroot=chroot
log='log-output -t mythbuntu'

mount -t proc none $ROOT/proc
mount -t devpts none $ROOT/dev/pts
mount -t sysfs sysfs $ROOT/sys

#to run X apps as a different hostname
NEW_HOSTNAME=$(cat $ROOT/etc/hostname)
xhost + local:""
sed -i s/ubuntu$/ubuntu\ $NEW_HOSTNAME/ /etc/hosts

#Start mysql if necessary
if $chroot $ROOT dpkg -l | grep mysql-server >/dev/null; then
    $log $chroot $ROOT invoke-rc.d mysql start
    mkdir -p /var/run/mysqld
    $log mount --bind $ROOT/var/run/mysqld /var/run/mysqld
fi

#Prepare login info
mkdir -p $HOME/.mythtv
rm -f $HOME/.mythtv/mysql.txt
ln -s /target/etc/mythtv/mysql.txt $HOME/.mythtv/mysql.txt

#Set our new hostname
hostname $NEW_HOSTNAME

#Run Mythtv-setup
xterm -e mythtv-setup.real

#Fill Database
zenity --title "Fill Database?" --question --text "Would you like to run mythfilldatabase?"
DATABASE_NOT=\$?
if [ "\$DATABASE_NOT" = "0" ]; then
    xterm -title "Running mythfilldatabase" -e "unset DISPLAY && unset SESSION_MANAGER && mythfilldatabase; sleep 3"
fi

#Stop MySQL if we started it
if $chroot $ROOT invoke-rc.d mysql status >/dev/null; then
    $log umount /var/run/mysqld
    $log $chroot $ROOT invoke-rc.d mysql stop
fi

#to clean up the whole procedure
umount $ROOT/proc
umount $ROOT/sys
umount $ROOT/dev/pts
