#!/bin/sh

set -e

if [ "$1" = "eth0" ]; then
	cat <<EOF
eth0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
	ether 2:44:66:88:aa:cc
	inet6 fe80::44:66ff:fe88:aacc%re0 prefixlen 64 scopeid 0x1 
	inet 0.0.0.0 netmask 0xff000000 broadcast 255.255.255.255
	inet6 2001:db8::44:66ff:fe88:aacc prefixlen 64 autoconf 
	nd6 options=3<PERFORMNUD,ACCEPT_RTADV>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
EOF
fi
