#! /bin/sh
#
# Test PEP-8 conformance.

pep8 --exclude keyboard_names.py --exclude Keyboard.py \
    --ignore=E402 \
    $(grep -lr '#!.*bin/python' bin) \
    scripts tests tests/run tests/run-frontend ubiquity autopilot
