#! /bin/sh
#
# Test PEP-8 conformance.

# FIXME: re-enable W504 and update for new breaking rules for binary op
pep8 --exclude keyboard_names.py --exclude Keyboard.py \
    --ignore=E402,W504 \
    --max-line-length=119 \
    $(grep -lr '#!.*bin/python' bin) \
    scripts tests tests/run tests/run-frontend ubiquity autopilot
