#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = hfs ]; then
		>/var/lib/partman/hfs
		exit 0
	fi
done

if modprobe hfs; then
	>/var/lib/partman/hfs
	exit 0
fi

if grep -q hfs /proc/filesystems; then
	>/var/lib/partman/hfs
fi
