#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = reiserfs ]; then
		>/var/lib/partman/reiserfs
		exit 0
	fi
done

if modprobe reiserfs >/dev/null 2>/dev/null; then
	>/var/lib/partman/reiserfs
	exit 0
fi

if grep -q reiserfs /proc/filesystems; then
	>/var/lib/partman/reiserfs
fi
