#! /bin/sh -e
# Disable 'auto dhcp' interfaces if network-manager is in use.

. /usr/share/debconf/confmodule

db_get netcfg/network-manager
if [ "$RET" = true ] && \
   [ -f /target/usr/lib/network-manager/ifblacklist_migrate.sh ]; then
	NETCFG=1 chroot /target \
		sh /usr/lib/network-manager/ifblacklist_migrate.sh
fi

exit 0
