#! /bin/sh
# Some scripts use this to figure out the architecture. In ubiquity, just
# call dpkg instead, except that --print-os needs a bit of special-casing.
if [ "$1" = --print-os ]; then
    # TODO: hardcoded for now
    echo linux
else
    exec dpkg "$@"
fi
