#!/bin/sh

. /usr/share/debconf/confmodule

[ -e /var/lib/partman/efi ] || exit 0

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

[ -f $id/method ] || exit 0
method=$(cat $id/method)

case "$method" in
    efi)
	db_metaget partman/method_short/efi description || RET=''
	printf "${RET:-efi}" >$id/visual_filesystem
	>$id/visual_mountpoint
	;;
esac
