.Dd January 10, 2011
.Os Debian
.ds volume-operating-system Debian
.Dt ARCHDETECT 1
.Sh NAME
.Nm archdetect
.Nd detect hardware architecture
.Sh SYNOPSIS
.Nm
.Op Fl g
.Sh DESCRIPTION
.Nm
displays the current machine architecture and subarchitecture.
The architecture corresponds to that built into
.Ic dpkg ,
and describes the CPU (and possibly kernel) types; the subarchitecture
distinguishes machines with different boot arrangements that require special
handling.
.Pp
The following option is available:
.Bl -tag -width 4n
.It Fl g
When bringing up new subarchitectures,
.Nm
may not yet have been taught about this specific machine.
This option asks that
.Nm
try to guess a generic subarchitecture that may be compatible with this
machine.
This is only necessary on certain architectures, and simply has no effect
elsewhere.
.El
.Sh AUTHORS
.Nm
was written by the Debian Installer team.
