.Dd December 22, 2008
.Os Ubuntu
.ds volume-operating-system Ubuntu
.Dt OEM\-CONFIG\-PREPARE 8
.Sh NAME
.Nm oem\-config\-prepare
.Nd prepare system for shipping to end user
.Sh SYNOPSIS
.Nm
.Op Fl Fl quiet
.Sh DESCRIPTION
.Nm
arranges for
.Xr oem\-config\-firstboot 8
to be run the next time the system boots.
It removes some machine-specific files such as persistent udev rules and
.Xr ssh 1
.Pa known_hosts
files that should not be duplicated to cloned machines.
.Pp
The following options are available:
.Bl -tag -width 4n
.It Fl Fl quiet
Do not display a confirmation message.
.El
.Sh AUTHOR
.An Colin Watson Aq cjwatson@ubuntu.com
.Pp
.An -nosplit
.Ic oem\-config
is copyright \(co 2005, 2006, 2007, 2008
.An Canonical Ltd . ,
and
copyright \(co 2006, 2007
.An Anirudh Ramesh .
See the GNU General Public License version 2 or later for copying
conditions.
A copy of the GNU General Public License is available in
.Pa /usr/share/common\-licenses/GPL .
