#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    install|upgrade)
        dpkg-divert --package ubiquity-frontend-mythbuntu --add --rename \
                    --divert /usr/share/ubiquity/ubiquity-gtkui.desktop.diverted /usr/share/applications/ubiquity-gtkui.desktop
        dpkg-divert --package ubiquity-frontend-mythbuntu --add --rename \
                    --divert /usr/share/pixmaps/ubiquity-diverted.png /usr/share/pixmaps/ubiquity.png
        ;;
esac

