desktop/ubiquity-kdeui.desktop usr/share/applications/kde4
ubiquity/frontend/kde_ui.py usr/lib/ubiquity/ubiquity/frontend
ubiquity/frontend/kde_components/* usr/lib/ubiquity/ubiquity/frontend/kde_components

pixmaps/kubuntu-install.png usr/share/ubiquity/pixmaps
pixmaps/kubuntu-live-session.png usr/share/ubiquity/pixmaps

gui/qt/*.ui usr/share/ubiquity/qt
gui/qt/*.qss usr/share/ubiquity/qt
gui/qt/images/*.png usr/share/ubiquity/qt/images
