#!/bin/sh
while read line; do
	set -- $line
        if echo "$2" | grep -qs "\(/cdrom\|/media/cdrom\)"; then
                fs="$(block-attr --type "$1" || true)"
                if [ -n "$fs" ] && [ "$fs" != "iso9660" ] && [ "$fs" != "udf" ]; then
                        :
                else
                        echo "$line"
                fi
        else
                echo "$line"
        fi
done < /target/etc/fstab > /target/etc/fstab.new
mv /target/etc/fstab.new /target/etc/fstab
