#!/bin/sh

dev=$2
id=$3

mkdir -p $dev/$id

echo efi >$dev/$id/method
>$dev/$id/format
>$dev/$id/bootable
>$dev/$id/efi_bootable

rm -f $dev/$id/use_filesystem
rm -f $dev/$id/filesystem
rm -f $dev/$id/mountpoint

exit 0
