initramfs-hook/flash-kernel     etc/initramfs/post-update.d
kernel-hook/zz-flash-kernel     etc/kernel/postinst.d
kernel-hook/zz-flash-kernel     etc/kernel/postrm.d
flash-kernel                    usr/sbin
initramfs-tools                 usr/share
bootscript                      usr/share/flash-kernel
db                              usr/share/flash-kernel
functions                       usr/share/flash-kernel
