#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = ext2 ]; then
		>/var/lib/partman/uboot
		exit 0
	fi
done

if modprobe ext2 >/dev/null 2>/dev/null; then
	>/var/lib/partman/uboot
	exit 0
fi

if grep -q ext2 /proc/filesystems; then
	>/var/lib/partman/uboot
fi
