.TH ckbcomp 1 "MAY 2007" console\-setup "User Manuals"
.SH NAME
ckbcomp \- compile a XKB keyboard description to a keymap suitable for loadkeys
.SH SYNOPSIS
.B ckbcomp
.RI [ option \ ...] \ [layout \ [variant \ [option \ ...]]]
.SH DESCRIPTION
The
.B ckbcomp
keymap compiler converts a description of an XKB keymap into a console
keymap that can be read directly by loadkeys.
.SH OPTIONS
.TP
.B \-?\fR, \fP\-help
Print a usage message and exit.
.TP
.B \-charmap\  charmap
The encoding to use.
There should be an unicode ACM map for this encoding in 
.IR /usr/share/consoletrans .
.TP
.BI \-I dir
Search top-level directory
.I dir
for files included by the keymap description.
This option may be used multiple times.
After all directories specified by
.B \-I
options have been searched,
.IR /etc/console\-setup/ckb ,
.IR /usr/share/X11/xkb ,
.IR /etc/X11/xkb
and
.IR /usr/X11R6/lib/X11/xkb
will be searched too.
.TP
.BI \-v\  level
Set level of detail for listing.
.I level
is a number from 1 to 10.
.TP
.BI \-compact
Generate a compact keymap with at most two xkb groups and two levels
in each or only one xkb-group and up to four levels.
.SH "XKB KEYBOARD DESCRIPTION"
The keyboard layout, variant and options components can be also
specified directly on the command line.
See the synopsis of the command.
.TP
.BI \-symbols \ name
Specifies the symbols component name of the XKB keyboard description.
.TP
.BI \-keycodes \ name
Specifies the keycodes component name of the XKB keyboard description.
.TP
.BI \-rules \ name
The name of the rules file to use.
.TP
.BI \-model \ name
Specifies the keyboard model used to choose the component names.
.TP
.BI \-layout \ name
Specifies the layout used to choose the component names.
.TP
.BI \-variant \ name
Specifies the layout variant used to choose the component names.
.TP
.BI \-option \ name
Adds an option used to choose component names.
.SH "SEE ALSO"
.BR xkbcomp (1)
.SH AUTHOR
Anton Zinoviev <anton@lml.bas.bg>, <zinoviev@debian.org>
