#! /bin/sh
set -e

. /usr/share/debconf/confmodule

mkdir -p /target/etc/default
cp -a /etc/default/console-setup /target/etc/default/
chroot /target setupcon --save-only

apt-install console-setup || true

exit 0
