#! /bin/sh
set -e

. /usr/share/debconf/confmodule

CONT="true"
while [ "$CONT" = true ]; do
	/usr/lib/ubiquity/migration-assistant/ma-ask /usr/lib/ubiquity/migration-assistant || break
	db_input high ubiquity/run-ma-again || true
	db_go || true
	db_get ubiquity/run-ma-again
	CONT="$RET"
	db_fset ubiquity/run-ma-again seen false
done
