#!/bin/sh

. /lib/partman/lib/base.sh

uboot=no

for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	cd $dev
	partitions=
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ "$fs" != free ] || continue
		[ -f $id/method -a -f $id/acting_filesystem ] || continue
		filesystem=$(cat $id/acting_filesystem)
		case $filesystem in
		    uboot)
			uboot=yes
			;;
		esac
	done
	close_dialog
done

if [ "$uboot" = yes ]; then
	apt-install e2fsprogs || true
fi
