.\"Copyright (C) 2007, 2011 Anton Zinoviev <anton@lml.bas.bg>
.\"
.\"Copying and distribution of this file, with or without
.\"modification, are permitted in any medium without royalty provided
.\"the copyright notice and this notice are preserved.  This file is
.\"offered as-is, without any warranty.
.\"
.TH SETUPCON 1 2011-03-17 console-setup "Console-setup User's Manual"

.SH NAME
setupcon \- sets up the font and the keyboard on the console

.SH SYNOPSIS
.B setupcon
.RI [ OPTION ]...\ [ VARIANT ]

.SH DESCRIPTION
.B setupcon
is a program for fast and easy setup of the font and the keyboard on
the console.  Most of the time you invoke
.B setupcon
without arguments.  The keyboard configuration is specified in
.I ~/.keyboard
or
.IR /usr/local/etc/default/keyboard .
The font configuration is specified in
.I ~/.console-setup
or
.IR /usr/local/etc/default/console-setup .
Consult
.BR keyboard (5)
and
.BR console-setup (5)
for instructions how to configure these two files.
.P
If you have to switch often between different encodings, keyboards or
languages, you can prepare several alternative configuration files for
.BR setupcon .
Suppose that most of the time you will use Greek language with Greek
keyboard layout, but sometimes you need to type in German with German
keyboard layout.  In this situation you should customize the main
configuration files
.nh
.RI ( keyboard " and " console-setup )
.hy
for Greek.  Create also alternative configuration files for German
named
.nh
.IR keyboard.german " and " console-setup.german .
.hy
Then in order to configure the console for Greek you will simply run
the command with no arguments:
.I setupcon
and in order to configure the console for German you will use
.nh
.IR setupcon\ german .
.hy


.SH OPTIONS

.TP
.BR -v ,\  --verbose
Be more verbose.   Use this option if something goes wrong or while
experimenting with the configuration files.

.TP
.BR -k ,\  --keyboard-only
Setup the keyboard only, do not setup the font.

.TP
.BR -f ,\  --font-only
Setup the font only, do not setup the keyboard.

.TP
.BR --force
Do not check whether we are on the console.  Notice that you can be
forced to hard-reboot your computer if you run
.B setupcon
with this option and the screen is controlled by a X server.

.TP
.BR --save
This option can be useful if you want to use
.B setupcon
early in the boot process while
.I /usr
is not yet mounted and the required data are not available.  This
option will make
.B setupcon
copy the required files in
.I /etc/console-setup/
in order to make them available before
.I /usr
is mounted.  If you use
.B setupcon
early in the boot process, then you should run it with this option
after every change of the console configuration.

.TP
.BR --save-only
The same as
.IR --save ,
but does not setup the keyboard and the font.  This option can be
useful if you want to save the required files while the screen is
controlled by a X server.

.TP
.BR -h ,\  --help
Display usage information.

.TP
.IR VARIANT
Specifies which configuration file to use.  By default the
configuration files of
.B setupcon
are named
.IR console-setup " and " keyboard
but if you use e.g.
.I chukchi
as
.I VARIANT
then the configuration files will be
.IR console-setup.chukchi " and " keyboard.chukchi .
In this way you can have easy access to several different
configurations \- for example one for the Chukchi language and another
for the default configuration.

.SH FILES
.I ~/.console-setup
.br
.I ~/.keyboard
.br
.I /usr/local/etc/default/console-setup
.br
.I /usr/local/etc/default/keyboard
.br
.I /usr/local/etc/default/console-setup.VARIANT
.br
.I /usr/local/etc/default/keyboard.VARIANT
.br
.I /etc/console-setup/

.SH SEE ALSO
.BR keyboard (5),
.BR console-setup (5)
