#!/bin/sh

. /usr/share/debconf/confmodule

if [ -x /bin/archdetect ]; then
	arch=$(archdetect)
else
	arch=unknown/generic
fi

db_reset partman-target/arch_help/$arch
db_subst partman-target/arch_help/$arch BOOTABLE 'B'

db_reset partman-target/help
db_metaget partman-target/arch_help/$arch description || RET=''
db_subst partman-target/help ARCHITECTURE_HELP  "$RET"
db_subst partman-target/help KEEP 'K'
db_subst partman-target/help DESTROY 'F'
db_subst partman-target/help FORMAT 'f'

db_input critical partman-target/help
db_go

exit 0
