#!/bin/sh

# Copyright (C) 2011  Loïc Minier <lool@dooz.org>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
# USA.

. ./testlib

flash_kernel="${FK_CHECKOUT:-$FK_DIR}/flash-kernel"

test_syntax() {
    sh -n "$flash_kernel"
}
add_test test_syntax

skip_test_bashisms() {
    if which checkbashisms 2>&1 >/dev/null; then
        return 1
    fi
    return 0
}

test_bashisms() {
    checkbashisms "$flash_kernel"
}
add_test test_bashisms


test_main

# vim:syntax=sh
